### PR TITLE
The Big One™ 

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by pthariensflame** [comment]
Tell me whenever this is ready for review.  :)

**Comment by CodaFi** [comment]
Eyy, ready.

**Comment by pthariensflame** [comment]
:+1: :boat:

**Comment by pthariensflame** [comment]
@CodaFi Would you mind filling in the release notes, now that I've created the tag?  I can't remember what changes went in since the last one.

**Comment by CodaFi** [comment]
It would be an honor and a pleasure to do so.

**Pull request merged**
