### PR TITLE
Re-Categorize Operators

### PR DESCRIPTION
**Pull request by CodaFi**
I think I may have finally teased-out what you were going for originally.  The operators are grouped by their respective Categories now and the docs have been updated to reflect which operator they _actually_ map to back in `pipes`.

### CODE REVIEW

**Comment by CodaFi** [comment]
I think it's worth it to move all of these operator declarations into a new file.  They really clutter up the interface here.

**Comment by pthariensflame** [comment]
@CodaFi Probably a good idea.  If you want to do that, I'll wait to merge this until then.  Otherwise:  :+1:!

**Comment by CodaFi** [comment]
I think that settles that.

Ready for review.

**Comment by pthariensflame** [comment]
Yay!  :tada:

**Pull request merged**
