### PR TITLE
Update to Swift 3.0

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by pthariensflame** [comment]
There are a bunch of places where you replaced `R>.T` with `>` and now have a dangling comma as a result!  😆

**Comment by CodaFi** [comment]
Good catch!  Should be in docs only.  Xcode's visual regular expression matcher was off-by-a-capture-group for some reason.

**Comment by pthariensflame** [comment]
I'm also not entirely convinced of the correctness of the new precedence group assignments.  It seems to me that we should follow the lead of the `pipes` library from whence we came, at least as far as relative precedence goes.

**Comment by CodaFi** [comment]
Agreed.  I'll redo them tomorrow.

**Comment by CodaFi** [comment]
@pthariensflame How does it look?

**Comment by pthariensflame** [comment]
👍 ⛵

**Comment by pthariensflame** [comment]
`swift-develop` is now protected!

**Pull request merged**
